### ISSUE TITLE
Milvus doesnt work with Nginx Ingress

### ISSUE THREAD

**Issue by wallies** [milvus-io/milvus-helm#313]
Milvus 2.0.1 works when pointing it straight at the service in GKE but when I try to use an ingress with class nginx it doesnt work. I even tried with the following annotations:
```
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy_buffers: "8 8k"
    nginx.ingress.kubernetes.io/server-snippet: grpc_read_timeout 3600s; grpc_send_timeout 3600s;
```

**Comment by haorenfsa** [comment]
hi, In my exp, maybe you should specify your ingress listen port like `nginx.org/listen-ports` or `nginx.org/listen-ports-ssl` with your intentional port, by default they're 80, 443 which is not the milvus usually port 19530
more info see:
https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/
